### ISSUE TITLE
TODO 2020-05-25

### ISSUE THREAD

**Issue by golden-dawn** [golden-dawn/c#58]
- [X] Make sure the index download works properly
  - [X] Upload the indexes historical data missing from the database
  - [X] Run the EOD or intraday script and check that the index data is in the database
- X Do not run the analysis on holidays, instead send an email saying that the market is closed.
- [X] Separate the option downloads in two files, one for each expiry
- [X] On expiry dates, run a 3:55PM script that will download the options for the current expiration.  Do not run the script the other days
- [ ] Implement the new analysis that combines `JC_5DAYS` with scored setups and JL trends.
  - [ ] Identify all the stocks that are in a 1.5 or 2 factor uptrend or downtrend
  - [ ] Calculate the setup score for these stocks
  - [ ] Add the OBV from the last pivot / non-secondary record to the score.
  - [ ] Produce, every day, a list of 8 setups, ordered by the absolute value of the score.
- [X] Ensure index downloading does not interfere with downloading for other stocks

**Comment by golden-dawn** [comment]
Replaced by TODO 2020-08-05
